name: Python Unit Tests

on:
  workflow_call:
 
permissions:
  contents: read

jobs:
  build-python:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:

    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Setup project build variables
      run: |
        for i in `cat conf/buildvars.properties` ; do echo "$i" >> $GITHUB_ENV ; done

    - name: Setup Python ${{ env.PYTHON_VERSION }} interpreter
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Setup Python dependency modules
      run: |
        python -m pip install --upgrade pip
        pip install -r ./conf/python/build.txt -r ./conf/python/runtime.txt

    - name: Run Unit Tests
      run: |
        python -m nose2 -v -F -s ${{ env.UNIT_TEST_DIR }} -t .


    

  